project_id = "aesmsmguyxehseshzxyt"

[functions.request-mikrotik]
verify_jwt = false

[functions.customer-auth]
verify_jwt = false

[functions.customer-auto-login]
verify_jwt = false

[functions.check-data-limit]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.mikrotik-sync]
verify_jwt = false

[functions.login-lookup]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.update-admin-account]
verify_jwt = false

[functions.bkash-payment]
verify_jwt = false