import { useState, useMemo, useEffect } from 'react';
import { useSearchParams, useNavigate } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { startOfMonth, endOfMonth, isWithinInterval, startOfDay, endOfDay } from 'date-fns';
import { DashboardLayout } from '@/components/layout/DashboardLayout';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { useRadiusUsers } from '@/hooks/useRadiusUsers';
import { Skeleton } from '@/components/ui/skeleton';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { DollarSign, Users, UserX, Wallet, Search } from 'lucide-react';
import { RechargeDialog } from '@/components/recharge/RechargeDialog';
import { DateRangeFilter } from '@/components/finance/DateRangeFilter';
import { supabase } from '@/integrations/supabase/client';
import type { Tables } from '@/integrations/supabase/types';

type RadiusUser = Tables<'radius_users'> & {
  plan?: Tables<'billing_plans'> | null;
};

export default function BillingStatistics() {
  const { data: users = [], isLoading } = useRadiusUsers();
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();

  // Fetch auto-generated transactions
  const { data: autoGeneratedTransactions = [], isLoading: autoTxLoading } = useQuery({
    queryKey: ['auto-generated-transactions'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('transactions')
        .select(`
          *,
          radius_user:radius_users(id, username, full_name)
        `)
        .eq('is_auto_generated', true)
        .eq('status', 'completed')
        .order('created_at', { ascending: false });
      if (error) throw error;
      return data || [];
    },
  });
  
  // Filter states
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState<string>('all');
  const [billingTypeFilter, setBillingTypeFilter] = useState<string>('all');
  const [paidFilter, setPaidFilter] = useState<string>('all');
  const [startDate, setStartDate] = useState<Date | undefined>(startOfMonth(new Date()));
  const [endDate, setEndDate] = useState<Date | undefined>(endOfMonth(new Date()));
  
  // Recharge dialog state
  const [selectedUser, setSelectedUser] = useState<RadiusUser | null>(null);
  const [isRechargeDialogOpen, setIsRechargeDialogOpen] = useState(false);

  const handleRecharge = (user: RadiusUser) => {
    setSelectedUser(user);
    setIsRechargeDialogOpen(true);
  };

  // Read URL params on mount
  useEffect(() => {
    const status = searchParams.get('status');
    const paid = searchParams.get('paid');
    const billing = searchParams.get('billing');
    
    if (status) {
      setStatusFilter(status);
    }
    if (paid === 'true') {
      setPaidFilter('paid');
    }
    if (billing === 'auto_renew') {
      setPaidFilter('auto_renew');
    }
  }, [searchParams]);

  // Calculate billing statistics
  const stats = useMemo(() => {
    const activeUsers = users.filter(u => u.status === 'active');
    const expiredUsers = users.filter(u => u.status === 'expired');

    return {
      totalBill: users.reduce((sum, u) => sum + (u.monthly_bill || 0), 0),
      activeUsersBill: activeUsers.reduce((sum, u) => sum + (u.monthly_bill || 0), 0),
      expiredUsersBill: expiredUsers.reduce((sum, u) => sum + (u.monthly_bill || 0), 0),
    };
  }, [users]);

  // Filter users
  const filteredUsers = useMemo(() => {
    return users.filter(user => {
      const matchesSearch = 
        user.username.toLowerCase().includes(searchTerm.toLowerCase()) ||
        (user.full_name || '').toLowerCase().includes(searchTerm.toLowerCase()) ||
        (user.phone || '').toLowerCase().includes(searchTerm.toLowerCase());
      
      const matchesStatus = statusFilter === 'all' || user.status === statusFilter;
      const matchesBillingType = billingTypeFilter === 'all' || user.billing_type === billingTypeFilter;
      const matchesPaid = paidFilter === 'all' || paidFilter === 'auto_renew' || paidFilter === 'paid' || paidFilter === 'unpaid';

      // Date filter on created_at
      let matchesDate = true;
      if (startDate || endDate) {
        const userDate = new Date(user.created_at);
        if (startDate && endDate) {
          matchesDate = isWithinInterval(userDate, { start: startOfDay(startDate), end: endOfDay(endDate) });
        } else if (startDate) {
          matchesDate = userDate >= startOfDay(startDate);
        } else if (endDate) {
          matchesDate = userDate <= endOfDay(endDate);
        }
      }
      
      return matchesSearch && matchesStatus && matchesBillingType && matchesPaid && matchesDate;
    });
  }, [users, searchTerm, statusFilter, billingTypeFilter, paidFilter, startDate, endDate]);

  const getStatusBadge = (status: string) => {
    const variants: Record<string, { variant: 'default' | 'secondary' | 'destructive' | 'outline'; label: string }> = {
      active: { variant: 'default', label: 'Active' },
      expired: { variant: 'destructive', label: 'Expired' },
      disabled: { variant: 'secondary', label: 'Disabled' },
      suspended: { variant: 'outline', label: 'Suspended' },
    };
    const config = variants[status] || { variant: 'secondary', label: status };
    return <Badge variant={config.variant}>{config.label}</Badge>;
  };

  const StatCard = ({ title, value, icon: Icon, subtitle }: { 
    title: string; 
    value: string | number; 
    icon: React.ElementType; 
    subtitle?: string;
  }) => (
    <Card className="bg-card border-border">
      <CardHeader className="flex flex-row items-center justify-between pb-2">
        <CardTitle className="text-sm font-medium text-muted-foreground">{title}</CardTitle>
        <Icon className="w-4 h-4 text-primary" />
      </CardHeader>
      <CardContent>
        <div className="text-2xl font-bold">{isLoading ? <Skeleton className="h-8 w-20" /> : value}</div>
        {subtitle && <p className="text-xs text-muted-foreground mt-1">{subtitle}</p>}
      </CardContent>
    </Card>
  );

  return (
    <DashboardLayout title="Billing Statistics" subtitle="Overview of billing and payment metrics">
      {/* Summary Stats */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
        <StatCard 
          title="Total Bill" 
          value={`৳${stats.totalBill.toLocaleString()}`} 
          icon={DollarSign}
          subtitle="All users monthly bill"
        />
        <StatCard 
          title="Active Users Bill" 
          value={`৳${stats.activeUsersBill.toLocaleString()}`} 
          icon={Users}
          subtitle="Active users monthly bill"
        />
        <StatCard 
          title="Expired Users Bill" 
          value={`৳${stats.expiredUsersBill.toLocaleString()}`} 
          icon={UserX}
          subtitle="Expired users monthly bill"
        />
      </div>

      {/* Filters */}
      <Card className="bg-card border-border mb-6">
        <CardHeader>
          <CardTitle className="text-lg">Filter Users</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex flex-wrap items-center gap-4 mb-4">
            <DateRangeFilter
              startDate={startDate}
              endDate={endDate}
              onStartDateChange={setStartDate}
              onEndDateChange={setEndDate}
              onClear={() => { setStartDate(undefined); setEndDate(undefined); }}
            />
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
              <Input
                placeholder="Search by username, name, or phone..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="pl-10"
              />
            </div>
            <Select value={statusFilter} onValueChange={setStatusFilter}>
              <SelectTrigger>
                <SelectValue placeholder="Filter by Status" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Status</SelectItem>
                <SelectItem value="active">Active</SelectItem>
                <SelectItem value="expired">Expired</SelectItem>
                <SelectItem value="disabled">Disabled</SelectItem>
                <SelectItem value="suspended">Suspended</SelectItem>
              </SelectContent>
            </Select>
            <Select value={billingTypeFilter} onValueChange={setBillingTypeFilter}>
              <SelectTrigger>
                <SelectValue placeholder="Filter by Billing Type" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Billing Types</SelectItem>
                <SelectItem value="prepaid">Prepaid</SelectItem>
                <SelectItem value="postpaid">Postpaid</SelectItem>
              </SelectContent>
            </Select>
            <Select value={paidFilter} onValueChange={setPaidFilter}>
              <SelectTrigger>
                <SelectValue placeholder="Filter by Payment" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Users</SelectItem>
                <SelectItem value="paid">Already Paid</SelectItem>
                <SelectItem value="unpaid">Unpaid</SelectItem>
                <SelectItem value="auto_renew">Auto Renew</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </CardContent>
      </Card>

      {/* Users Table / Auto Renew Transactions */}
      <Card className="bg-card border-border">
        <CardHeader>
          <CardTitle className="text-lg">
            {paidFilter === 'auto_renew' ? `Auto Renew Bill (${autoGeneratedTransactions.length})` : `All Users with Bill (${filteredUsers.length})`}
          </CardTitle>
        </CardHeader>
        <CardContent>
          {(paidFilter === 'auto_renew' ? autoTxLoading : isLoading) ? (
            <div className="space-y-2">
              {[...Array(5)].map((_, i) => (
                <Skeleton key={i} className="h-12 w-full" />
              ))}
            </div>
          ) : paidFilter === 'auto_renew' ? (
            <div className="rounded-md border">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Username</TableHead>
                    <TableHead>Full Name</TableHead>
                    <TableHead className="text-right">Amount</TableHead>
                    <TableHead>Date</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {autoGeneratedTransactions.length === 0 ? (
                    <TableRow>
                      <TableCell colSpan={4} className="text-center text-muted-foreground py-8">
                        No auto-generated bills found
                      </TableCell>
                    </TableRow>
                  ) : (
                    autoGeneratedTransactions.map((tx: any) => (
                      <TableRow key={tx.id}>
                        <TableCell>
                          <button
                            onClick={() => tx.radius_user && navigate(`/users/${tx.radius_user.id}`)}
                            className="font-medium text-primary hover:underline cursor-pointer"
                          >
                            {tx.radius_user?.username || '-'}
                          </button>
                        </TableCell>
                        <TableCell>{tx.radius_user?.full_name || '-'}</TableCell>
                        <TableCell className="text-right">৳{Number(tx.amount).toLocaleString()}</TableCell>
                        <TableCell>{new Date(tx.created_at).toLocaleDateString()}</TableCell>
                      </TableRow>
                    ))
                  )}
                </TableBody>
              </Table>
            </div>
          ) : (
            <div className="rounded-md border">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Username</TableHead>
                    <TableHead>Full Name</TableHead>
                    <TableHead>Phone</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead>Billing Type</TableHead>
                    <TableHead className="text-right">Monthly Bill</TableHead>
                    <TableHead className="text-center">Grace</TableHead>
                    <TableHead className="text-right">Action</TableHead>
                    <TableHead className="text-right">Action</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {filteredUsers.length === 0 ? (
                    <TableRow>
                      <TableCell colSpan={9} className="text-center text-muted-foreground py-8">
                        No users found matching your filters
                      </TableCell>
                    </TableRow>
                  ) : (
                    filteredUsers.map((user) => (
                      <TableRow key={user.id}>
                        <TableCell>
                          <button
                            onClick={() => navigate(`/users/${user.id}`)}
                            className="font-medium text-primary hover:underline cursor-pointer"
                          >
                            {user.username}
                          </button>
                        </TableCell>
                        <TableCell>
                          <button
                            onClick={() => navigate(`/users/${user.id}`)}
                            className="hover:text-primary hover:underline cursor-pointer"
                          >
                            {user.full_name || '-'}
                          </button>
                        </TableCell>
                        <TableCell>{user.phone || '-'}</TableCell>
                        <TableCell>{getStatusBadge(user.status)}</TableCell>
                        <TableCell>
                          <Badge variant="outline" className="capitalize">
                            {user.billing_type || 'prepaid'}
                          </Badge>
                        </TableCell>
                        <TableCell className="text-right">
                          {(user.monthly_bill || 0) === 0 ? (
                            <Badge variant="secondary">Free</Badge>
                          ) : (
                            `৳${(user.monthly_bill || 0).toLocaleString()}`
                          )}
                        </TableCell>
                        <TableCell className="text-center">
                          {user.grace_days_used > 0 ? (
                            <Badge variant="outline" className="bg-warning/20 text-warning border-warning/30">
                              {user.grace_days_used}d
                            </Badge>
                          ) : (
                            <span className="text-muted-foreground">-</span>
                          )}
                        </TableCell>
                        <TableCell className="text-right">
                          <Button
                            size="sm"
                            onClick={() => handleRecharge(user)}
                            className="bg-gradient-primary text-primary-foreground"
                          >
                            <Wallet className="w-4 h-4 mr-1" />
                            Recharge
                          </Button>
                        </TableCell>
                      </TableRow>
                    ))
                  )}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Recharge Dialog */}
      <RechargeDialog
        user={selectedUser}
        open={isRechargeDialogOpen}
        onOpenChange={setIsRechargeDialogOpen}
      />
    </DashboardLayout>
  );
}
