import { useQuery } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';

interface DashboardStats {
  totalUsers: number;
  activeUsers: number;
  expiredUsers: number;
  suspendedUsers: number;
  disabledUsers: number;
  freeUsers: number;
  alreadyPaidUsers: number;
  totalVouchers: number;
  unusedVouchers: number;
  activeVouchers: number;
  totalRevenue: number;
  totalDataUsedMB: number;
  totalBill: number;
  activeUsersBill: number;
  expiredUsersBill: number;
  alreadyPaidBill: number;
  totalConnectionFee: number;
  totalExtraIncome: number;
  autoRenewUsers: number;
  autoRenewBill: number;
}

export function useDashboardStats() {
  return useQuery({
    queryKey: ['dashboard-stats'],
    queryFn: async (): Promise<DashboardStats> => {
      // Get user stats with balance, monthly_bill, and connection_fee (only admin-created users)
      const { data: users, error: usersError } = await supabase
        .from('radius_users')
        .select('status, data_used_mb, balance, monthly_bill, connection_fee, auto_renew')
        .is('reseller_id', null);

      if (usersError) throw usersError;

      // Get voucher stats
      const { data: vouchers, error: vouchersError } = await supabase
        .from('vouchers')
        .select('status');

      if (vouchersError) throw vouchersError;

      // Get transaction stats
      const { data: transactions, error: transactionsError } = await supabase
        .from('transactions')
        .select('amount, type, status')
        .eq('status', 'completed')
        .eq('type', 'payment');

      if (transactionsError) throw transactionsError;

      // Get manual income (extra income)
      const [incomeResult, autoTxResult] = await Promise.all([
        supabase.from('income').select('amount'),
        supabase.from('transactions').select('amount').eq('is_auto_generated', true).eq('status', 'completed'),
      ]);

      if (incomeResult.error) throw incomeResult.error;
      const incomeData = incomeResult.data;
      const autoGeneratedTx = autoTxResult.data || [];

      const totalUsers = users?.length || 0;
      const activeUsers = users?.filter(u => u.status === 'active').length || 0;
      const expiredUsers = users?.filter(u => u.status === 'expired').length || 0;
      const suspendedUsers = users?.filter(u => u.status === 'suspended').length || 0;
      const disabledUsers = users?.filter(u => u.status === 'disabled').length || 0;
      const freeUsers = users?.filter(u => (u.monthly_bill || 0) === 0).length || 0;
      const alreadyPaidUsers = users?.filter(u => (u.balance || 0) > 0).length || 0;
      const totalDataUsedMB = users?.reduce((sum, u) => sum + (u.data_used_mb || 0), 0) || 0;

      // Bill calculations
      const totalBill = users?.reduce((sum, u) => sum + (u.monthly_bill || 0), 0) || 0;
      const activeUsersBill = users?.filter(u => u.status === 'active').reduce((sum, u) => sum + (u.monthly_bill || 0), 0) || 0;
      const expiredUsersBill = users?.filter(u => u.status === 'expired').reduce((sum, u) => sum + (u.monthly_bill || 0), 0) || 0;
      const alreadyPaidBill = users?.filter(u => (u.balance || 0) > 0).reduce((sum, u) => sum + (u.monthly_bill || 0), 0) || 0;

      const totalVouchers = vouchers?.length || 0;
      const unusedVouchers = vouchers?.filter(v => v.status === 'unused').length || 0;
      const activeVouchers = vouchers?.filter(v => v.status === 'active').length || 0;

      const totalRevenue = transactions?.reduce((sum, t) => sum + t.amount, 0) || 0;

      // Connection fee total
      const totalConnectionFee = users?.reduce((sum, u) => sum + (u.connection_fee || 0), 0) || 0;

      // Auto renew stats
      const autoRenewUsers = users?.filter(u => u.auto_renew === true).length || 0;
      const autoRenewBill = autoGeneratedTx.reduce((sum, t) => sum + Number(t.amount), 0);

      // Extra income (manually added)
      const totalExtraIncome = incomeData?.reduce((sum, i) => sum + Number(i.amount), 0) || 0;

      return {
        totalUsers,
        activeUsers,
        expiredUsers,
        suspendedUsers,
        disabledUsers,
        freeUsers,
        alreadyPaidUsers,
        totalVouchers,
        unusedVouchers,
        activeVouchers,
        totalRevenue,
        totalDataUsedMB,
        totalBill,
        activeUsersBill,
        expiredUsersBill,
        alreadyPaidBill,
        totalConnectionFee,
        totalExtraIncome,
        autoRenewUsers,
        autoRenewBill,
      };
    },
    refetchInterval: 30000, // Refresh every 30 seconds
  });
}